### ISSUE TITLE
新機能リクエスト

### ISSUE THREAD

**Issue by Tyrone2333** [yicru/qrcode-with-ip-extension#1]
こんにちは、chromewebstore でこの拡張機能を見つけました。 すべてのローカル IP のリストをサポートし、対応する置換ボタンを提供してほしいと思います。 私のコンピュータには複数のローカル IP があるため、この機能は私にとって非常に重要です。

Hello, I found this extension on chromewebstore. I wish it would support listing all local IPs and provide corresponding replace buttons. My computer has multiple local IPs, so this feature is very important to me.

**Comment by yicru** [comment]
Hello, @Tyrone2333 

The new version with the IP selection dropdown is now live 🚀
If you have any feedback or further feature requests, please let me know.
Thanks for your suggestion !

![CleanShot 2023-12-15 at 00 16 21@2x](https://github.com/yicru/qrcode-with-ip-extension/assets/37892222/b3568411-f9d3-4d78-b587-8b67d4f43414)
